
gsap.set('.main', {position:'fixed', background:'#fff', width:'100%', maxWidth:'1200px', height:'100%', top:0, left:'50%', x:'-50%'})
gsap.set('.scrollDist', {width:'100%', height:'200%'})
gsap.timeline({scrollTrigger:{trigger:'.scrollDist', start:'top top', end:'bottom bottom', scrub:1}})
   // .fromTo('.sky', {y:0},{y:-200}, 0)
   // .fromTo('.cloud1', {y:100},{y:-800}, 0)
    .fromTo('.trigger-warning', {y:-50},{y:-700}, 0)
    //.fromTo('.cloud3', {y:-50},{y:-650}, 0)
    .fromTo('#watercolor-1', {y:-50},{y:-400}, 0)
   // .fromTo('.mountMg', {y:-30},{y:-250}, 0)
    .fromTo('#line1', {y:-50},{y:-700}, 0)
    .fromTo('.bee',{y: -50},{y:-1100},0)
    .fromTo('.container', {y:-50}, {y:-700},0)
    .fromTo('.dogwood', {y:-50}, {y:-400},0)
    .fromTo('#honeysuckle', {y:-50}, {y:-400}, 0)
    .fromTo('.state-wide', {y:-50}, {y:-700},0)
    .fromTo('.why', {y:-50}, {y:-700},0)
    .fromTo('#church', {y:-50}, {y:-400},0)
    .fromTo('#paper', {y:-50}, {y: -700}, 0)
    .fromTo('.end-illustration', {y:-50}, {y: -700},0)
    .fromTo('#bottom-paper', {y:-50}, {y: -400},0)
    .fromTo('.fg', {y:-50}, {y:-900},0)
    .fromTo('#watercolor-2', {y:-50},{y:-400}, 0)
    .fromTo('.final', {y:-50},{y:-700}, 0)
    .fromTo('.help', {y:-50},{y:-600}, 0)


$('#arrowBtn').on('mouseenter', (e)=>{ gsap.to('.arrow', {y:10, duration:0.8, ease:'back.inOut(3)', overwrite:'auto'}); })
$('#arrowBtn').on('mouseleave', (e)=>{ gsap.to('.arrow', {y:0, duration:0.5, ease:'power3.out', overwrite:'auto'}); })
$('#arrowBtn').on('click', (e)=>{ gsap.to(window, {scrollTo:innerHeight, duration:1.5, ease:'power1.inOut'}); }) // scrollTo requires the ScrollTo plugin (not to be confused w/ ScrollTrigger)